/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package canvas;

import canvas.view.ViewFactory;
import canvas.view.swing.SwingViewFactory;

public class App {
    public static void main(String[] args) {
        ViewFactory viewFactory = new SwingViewFactory();
        viewFactory.createView();
    }
}
